### ISSUE TITLE
Can't compile sprites, several errors

### ISSUE THREAD

**Issue by maxlefou** [pixeldothorse/pixel.horse#162]
I just can't compile sprites at all.

`gulp sprites` gives the following:
```
$ gulp sprites
[17:51:55] Using gulpfile ~/pixel.horse/gulpfile.js
[17:51:55] Starting 'sprites'...
[17:51:55] Starting 'warnAboutTscBeingDumb'...
You're probably about to see some warnings from tsc about not being able to find certain files.
Don't worry about these. It's a known issue regarding circular build dependencies. The build should continue despite these errors.
[17:51:55] Finished 'warnAboutTscBeingDumb' after 828 μs
[17:51:55] Starting 'npm run ts-tools'...

> pony-town@0.55.2 ts-tools /home/max/pixel.horse
> tsc --rootDir src/ts --outDir src/scripts --pretty -p tsconfig.tools.json

[17:52:12] Finished 'npm run ts-tools' after 17 s
[17:52:12] Starting 'sprites'...
Failed to load: assets-source/pony/eyes.psd: Invalid signature: 'vers' at 0x0

/home/max/pixel.horse/node_modules/ag-psd/dist/D:\Projects\github\ag-psd\src/psdReader.ts:144
		throw new Error(`Invalid signature: '${signature}' at 0x${offset.toString(16)}`);
        ^
Error: Invalid signature: 'vers' at 0x0
    at checkSignature (/home/max/pixel.horse/node_modules/ag-psd/dist/D:\Projects\github\ag-psd\src/psdReader.ts:144:9)
    at readHeader (/home/max/pixel.horse/node_modules/ag-psd/dist/D:\Projects\github\ag-psd\src/psdReader.ts:170:2)
    at Object.readPsd (/home/max/pixel.horse/node_modules/ag-psd/dist/D:\Projects\github\ag-psd\src/psdReader.ts:154:14)
    at Object.readPsd (/home/max/pixel.horse/node_modules/ag-psd/dist/D:\Projects\github\ag-psd\src/index.ts:22:9)
    at Object.openPsd (/home/max/pixel.horse/src/ts/tools/psd-utils.ts:15:15)
    at ponyPsd (/home/max/pixel.horse/src/ts/tools/create-sprites.ts:53:35)
    at createPonySprites (/home/max/pixel.horse/src/ts/tools/create-sprites.ts:1028:25)
    at createSprites (/home/max/pixel.horse/src/ts/tools/create-sprites.ts:1307:2)
    at Object.<anonymous> (/home/max/pixel.horse/src/ts/tools/create-sprites.ts:1403:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

and `npm run build-sprites` makes me wait hours to give me the following log in the end:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'webpack-prod', '--' ]
2 info using npm@6.12.1
3 info using node@v10.17.0
4 verbose run-script [ 'prewebpack-prod', 'webpack-prod', 'postwebpack-prod' ]
5 info lifecycle pony-town@0.55.2~prewebpack-prod: pony-town@0.55.2
6 info lifecycle pony-town@0.55.2~webpack-prod: pony-town@0.55.2
7 verbose lifecycle pony-town@0.55.2~webpack-prod: unsafe-perm in lifecycle true
8 verbose lifecycle pony-town@0.55.2~webpack-prod: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/max/pixel.horse/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/max/pixel.horse/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/max/pixel.horse/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle pony-town@0.55.2~webpack-prod: CWD: /home/max/pixel.horse
10 silly lifecycle pony-town@0.55.2~webpack-prod: Args: [ '-c',
10 silly lifecycle   'node --max_old_space_size=8192 node_modules/webpack-cli/bin/cli --config webpack.prod.js --progress --color' ]
11 silly lifecycle pony-town@0.55.2~webpack-prod: Returned: code: 137  signal: null
12 info lifecycle pony-town@0.55.2~webpack-prod: Failed to exec webpack-prod script
13 verbose stack Error: pony-town@0.55.2 webpack-prod: `node --max_old_space_size=8192 node_modules/webpack-cli/bin/cli --config webpack.prod.js --progress --color`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid pony-town@0.55.2
15 verbose cwd /home/max/pixel.horse
16 verbose Linux 4.19.0-6-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "webpack-prod" "--"
18 verbose node v10.17.0
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 137
22 error pony-town@0.55.2 webpack-prod: `node --max_old_space_size=8192 node_modules/webpack-cli/bin/cli --config webpack.prod.js --progress --color`
22 error Exit status 137
23 error Failed at the pony-town@0.55.2 webpack-prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
```

Haven't modified any files at all. ts-watch gives 0 errors, wds compiles succesfully and gulp dev refuses to work because "pony.bin" can't be found (which is normal i guess)

**Comment by BytewaveMLP** [comment]
You forgot to install Git LFS before cloning. Install [Git LFS](https://git-lfs.github.com/), run `git lfs pull` in your clone directory, then try `npm run build-sprites` again.
