### ISSUE TITLE
`gulp dev --sprites` fails to run if tools/output folder is missing

### ISSUE THREAD

**Issue by Stubenhocker1399** [pixeldothorse/pixel.horse#55]
```
Error: ENOENT: no such file or directory, open '/home/chris/pixel.horse/tools/output/noseMuzzleCanvas.png'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.writeFileSync (fs.js:1314:33)
    at Object.saveCanvas (/home/chris/pixel.horse/src/ts/tools/canvas-utils.ts:170:5)
    at getMuzzlesFromPsd (/home/chris/pixel.horse/src/ts/tools/create-sprites.ts:214:2)
    at createPonySprites (/home/chris/pixel.horse/src/ts/tools/create-sprites.ts:1022:2)
    at createSprites (/home/chris/pixel.horse/src/ts/tools/create-sprites.ts:1300:2)
    at Object.<anonymous> (/home/chris/pixel.horse/src/ts/tools/create-sprites.ts:1396:2)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
```

**Comment by BytewaveMLP** [comment]
I have a fix for this already, but it's coming as part of a larger build system fix.

**Comment by Stubenhocker1399** [comment]
Alright, very good, no rush.
